name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
      with:
        path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm build
